Repository S1-K4/ForkMe-BE, pull requests merged in 2025-08, with the labels that each got.

#25 feat: git 로그인 및 jwt 토큰 기능
  ForkMe-BE/build.gradle
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/jwt/JwtKeyConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/security/jwt/JwtTokenFilter.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/OAuth2AuthenticationSuccessHandler.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/controller/AuthController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/dto/CustomUserDetails.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/dto/LogoutRequestDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/dto/TokenRefreshRequestDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/dto/TokenRefreshResponseDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/entity/Auth.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/repository/AuthRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/service/AuthService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/service/AuthServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/service/CustomOAuth2UserService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/service/JwtTokenProvider.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/entity/User.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/repository/UserRepository.java
  ForkMe-BE/src/main/resources/application.properties
Labels: ✨Feature

#34 Feature/chatting redis / redis 통합 코드 일단 dev 에 병합하겠습니다!
  ForkMe-BE/build.gradle
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/entity/Yn.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisPublisher.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisSubscriber.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisViewerSessionService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/WebSocketConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/chatting_enum/ChattingMessageType.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/chatting_enum/RoomType.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/dto/ChattingMessageDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingMessage.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingParticipant.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingRoom.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/mongo_document/ChattingMessageDocument.java
  ForkMe-BE/src/main/resources/application.properties
Labels: 🛠️Refactor

#39 refactor: 채팅 리팩토링
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/chatting_enum/ChattingMessageType.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/chatting_enum/RoomType.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/controller/ChattingController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/controller/ChattingHistoryController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/dto/ChattingUserDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingMessage.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingParticipant.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingRoom.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/mongo_document/ChattingMessageDocument.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingMessageMongoRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingMessageRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingParticipantRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingRoomRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingHistoryService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingHistoryServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingServiceImpl.java
Labels: ✨Feature, 🛠️Refactor

#45 [Feature/project] 프로젝트 curd 로직 구현
  ForkMe-BE/build.gradle
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/entity/BaseTime.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/s3/S3Controller.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/s3/S3Service.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/exception/CustomException.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/security/.gitkeep
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/Repository/ApplyRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/Repository/ApplyTechStackRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/entity/Apply.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/.gitkeep
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/dto/CustomUserDetails.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/entity/Likes.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/repository/LikeRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/comment/entity/Comment.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/controller/ProjectController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProgressEnumDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectCreateFormDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectCreateRequestDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectDetailResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectListResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectUpdateFormDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/entity/Project.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/entity/ProjectMember.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/entity/ProjectProfile.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectMemberRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectPositionRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectProfileRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectTechStackRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/s3/Entity/S3Image.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/s3/Repository/S3Repository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/s3/dto/ProjectImageDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/reference/position/dto/PositionResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/reference/position/entity/Position.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/reference/position/repository/PositionRepsitory.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/reference/stack/dto/TechStackResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/reference/stack/entity/TechStack.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/reference/stack/repository/StackRepository.java
  ForkMe-BE/src/main/resources/application.properties
Labels: ✨Feature

#46 feat : webhook 관련 초기 설정 및 연결
  ForkMe-BE/build.gradle
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/CorsConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/.gitkeep
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/GithubHookSessionKeys.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/client/GithubWebhookClient.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/controller/WebhookController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/dto/PendingHookRequest.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/repository/WebhookRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/service/WebhookService.java
  ForkMe-BE/src/main/resources/application.properties
  ForkMe-BE/src/main/resources/static/webhook-tester.html
Labels: ✨Feature

#47 feat : feat: GitHub Webhook step-up OAuth 플로우 도입 및 웹훅 수신 안정화 #40
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/OAuth2AuthenticationSuccessHandler.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/service/CustomOAuth2UserService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/client/GithubWebhookClient.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/on_project/webhook/controller/WebhookController.java
  ForkMe-BE/src/main/resources/static/hook-result.html
  ForkMe-BE/src/main/resources/static/hook-test.html
Labels: ✨Feature

#49 Feature/webhook
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
Labels: 🧩fix

#60 [feature/like] 좋아요 기능 구현
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/exception/CustomException.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/controller/LikeController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/dto/LikeDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/repository/LikeRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/service/LikeService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/service/LikeServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectServiceImpl.java
Labels: ✨Feature

#66 feature/chatting <- dev merge 했습니다.
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/controller/ChattingController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/controller/ChattingHistoryController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/dto/ChattingUserDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/dto/PrivateChattingRoomResponse.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/entity/ChattingParticipant.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/mongo_document/ChattingMessageDocument.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingMessageRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingRoomRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingHistoryServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectMemberRepository.java
Labels: 🛠️Refactor

#69 feat: 로그인 후 기본 정보 기능 #68
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/OAuth2AuthenticationSuccessHandler.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/controller/UserController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/dto/SideBarResponseDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/dto/UserInfoResponseDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/dto/UserProfile.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/repository/UserRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/service/UserService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/user/service/UserServiceImpl.java
  ForkMe-BE/src/main/resources/static/login-success.html
Labels: ✨Feature

#81 [Feature/project] 프로젝트 탈퇴, 강퇴, 프로젝트 명 변경 로직구현
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/exception/CustomException.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/service/ApplyServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/controller/AuthController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/controller/ProjectController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectTitleUpdateDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/entity/Project.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/enums/ProjectStatus.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectMemberRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectServiceImpl.java
Labels: ✨Feature

#93 docs: 좋아요, 댓글, 신청서, 프로젝트 관련 API 스웨거 문서 작성 #86
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/controller/ApplyController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyCreateFormDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyCreateRequestDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyListResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyTechStackDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/service/ApplyServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/controller/CommentController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/dto/CommentResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/dto/CreateCommentDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/dto/UpdateCommentDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/controller/LikeController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/dto/LikeDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/controller/ProjectController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProgressEnumDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectCreateFormDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectCreateRequestDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectDetailResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectListResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectTechStackDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectTitleUpdateDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectUpdateFormDTO.java
Labels: 📝Docs

#99 [refactor/apply-project] 신청서, 프로젝트 코드 리팩토링
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/swagger/SwaggerConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/exception/CustomException.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/exception/GlobalExceptionHandler.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/controller/ApplyController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyListResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/dto/ApplyResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/entity/Apply.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/repository/ApplyRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/repository/ApplyTechStackRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/service/ApplyService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/service/ApplyServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/controller/CommentController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/dto/UpdateCommentDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/repository/CommentRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/service/CommentService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/comment/service/CommentServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/controller/LikeController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/entity/Likes.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/repository/LikeRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/service/LikeService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/like/service/LikeServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/controller/ProjectController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectCreateFormDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectCreateRequestDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectResponseDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/dto/ProjectTitleUpdateDTO.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/entity/Project.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/entity/ProjectProfile.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/enums/ProgressType.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectMemberRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectPositionRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/repository/ProjectTechStackRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/s3/repository/S3Repository.java
  ForkMe-BE/src/main/resources/application.properties
Labels: 🛠️Refactor

#105 Feature/chatting : 프로젝트 캐싱 쪽 나에게만 일어나는 버그 일부 수정했습니다.
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/WebSocketConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/auth/OAuth2AuthenticationSuccessHandler.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/presence/event/ChattingPresenceEventListener.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/controller/ProjectController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/project/service/ProjectServiceImpl.java
  ForkMe-BE/src/main/resources/static/chatting-test22.html
Labels: 🐞Bug

#116 Feature/chatting 신청서, 채팅에 알람기능이 추가됐습니다.
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisPublisher.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/common/redis/RedisSubscriber.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/config/springsecurity/SecurityConfig.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/global/exception/GlobalExceptionHandler.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/controller/AlarmController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/controller/AlarmHistoryController.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/dto/AlarmListResponse.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/dto/AlarmMessageRequest.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/dto/AlarmMessageResponse.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/entity/Alarm.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/mongo_document/AlarmMessageDocument.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/repository/AlarmMessageMongoRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/service/AlarmHistoryService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/service/AlarmHistoryServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/service/AlarmService.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/alarm/service/AlarmServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/apply/service/ApplyServiceImpl.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/dto/ChattingMessageDto.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/mongo_document/ChattingMessageDocument.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/repository/ChattingRoomRepository.java
  ForkMe-BE/src/main/java/com/S1_K4/ForkMe_BE/modules/chatting/service/ChattingServiceImpl.java
  ForkMe-BE/src/main/resources/application.properties
  ForkMe-BE/src/main/resources/static/alarm-test.html
  ForkMe-BE/src/main/resources/static/alarm-test2.html
  ForkMe-BE/src/main/resources/static/alarm-test3.html
  ForkMe-BE/src/main/resources/static/alarm-test4.html
  ForkMe-BE/src/main/resources/static/alarm.html
  ForkMe-BE/src/main/resources/static/alarm2.html
Labels: ✨Feature
